<%@ Page Title="" Language="C#" MasterPageFile="~/NestedMasterPage1.master" AutoEventWireup="true" CodeBehind="AdminCourses.aspx.cs" Inherits="PrometheusADMIN.AdminCourses" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CphAdminBody" runat="server">
    <div style="width:100%">
        <br /><br /><br /><br />
         <asp:GridView ID="GridView1" runat="server"  Width="557px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" HorizontalAlign="Center"></asp:GridView>
    </div>
  

</asp:Content>

