<%@ Page Title="" Language="C#" MasterPageFile="~/NestedMasterPage1.master" AutoEventWireup="true" CodeBehind="AdminTeachers.aspx.cs" Inherits="PrometheusADMIN.AdminTeachers" %>
<asp:Content ID="Content1" ContentPlaceHolderID="CphAdminBody" runat="server">
    <div style="width:100%">
        <br /><br /><br /><br />
        
        <asp:gridview runat="server"  HorizontalAlign="Center" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            <EditRowStyle BackColor="#999999" />
            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#E9E7E2" />
            <SortedAscendingHeaderStyle BackColor="#506C8C" />
            <SortedDescendingCellStyle BackColor="#FFFDF8" />
            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
        </asp:gridview>
        <br /><br />
        <asp:HyperLink runat="server" HorizontalAlign="center" style="margin-left:440px;margin-bottom:100px" Text="Add New Teacher" NavigateUrl="AdminAdTeacher.aspx"></asp:HyperLink>
        <br />
    </div>
</asp:Content>
